spring:
  application:
   name: employee-management-system
  data:
    uri: mongodb://localhost:27017
  eureka:
    instance:
      hostname: ${APPLICATION_DOMAIN}
      nonSecurePort: 80

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    serviceUrl:
      defaultZone: ${vcap.services.eureka-service.credentials.uri:http://127.0.0.1:8761}/eureka/